# Dockerfile
FROM python:3.11-slim

# Evita que o Python gere arquivos .pyc e garante logs em tempo real.
ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1
ENV POETRY_VIRTUALENVS_CREATE=false

# Instala dependências globais básicas
RUN pip install --no-cache-dir gunicorn flask poetry fastapi uvicorn

# Define o diretório de trabalho dentro do container
WORKDIR /app

# Expõe a porta que o Traefik vai escutar
EXPOSE 8000

# Comando padrão: Inicia o servidor Gunicorn buscando o arquivo main.py
CMD ["gunicorn", "--bind", "0.0.0.0:8000", "--workers", "1", "--threads", "4", "main:app"]